name: Delete file during workflow

on: [push]

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Delete a file
        run: rm -f path/to/your/file.txt

      - name: Confirm deletion
        run: |
          if [ ! -f path/to/your/file.txt ]; then
            echo "File deleted successfully."
          else
            echo "File still exists!"
          fi
